# -*- coding: utf-8 -*-
"""Untitled71.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diM7Uke5sQ4Uj9sjsZk-fcyDcRAOY8E6
"""

from __future__ import annotations

import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
# -*- coding: utf-8 -*-

import numpy as np, torch, torchvision, random
import torch as ch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, ConcatDataset
from itertools import product
from collections import defaultdict
from sklearn.metrics import roc_auc_score, roc_curve
from torch.optim.lr_scheduler import CosineAnnealingLR
from torchvision.models import resnet18



# --------------------------------------------------------------------------- #
# 0)  Seeding & helpers                                                       #
# --------------------------------------------------------------------------- #
def set_global_seed(seed:int):
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    try:
        torch.use_deterministic_algorithms(True)
    except Exception:
        pass
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def _seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

def _dash(x): return "–" if (x is None or x == "–") else x
def mean_std(a): return float(np.mean(a)), float(np.std(a))

# --------------------------------------------------------------------------- #
# 1)  ResNet-18 backbone                                                      #
# --------------------------------------------------------------------------- #
class ResNet18Backbone(nn.Module):
    def __init__(self, n_classes=10):  # Αλλαγή από 100 σε 10 κλάσεις
        super().__init__()
        try:
            base = torchvision.models.resnet18(weights=None)
        except TypeError:
            base = torchvision.models.resnet18(pretrained=False)

        # Modify first conv for CIFAR (32x32 images)
        base.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
        base.maxpool = nn.Identity()  # Remove initial maxpool

        self.features = nn.Sequential(*list(base.children())[:-1])
        in_feats = base.fc.in_features
        self.fc = nn.Linear(in_feats, n_classes)

    def forward(self, x):
        x = self.features(x).flatten(1)
        return self.fc(x)

    def get_features(self, x):
        x = self.features(x).flatten(1)
        return x

def resnet18_backbone(n_classes=10):  # Αλλαγή από 100 σε 10 κλάσεις
    return ResNet18Backbone(n_classes=n_classes)

# --------------------------------------------------------------------------- #
# 2)  Deep Ensemble with per-teacher seeds                                    #
# --------------------------------------------------------------------------- #
class TeacherEnsemble(nn.Module):
    def __init__(self, n=5, n_classes=10, base_seed=42):  # Αλλαγή από 100 σε 10 κλάσεις
        super().__init__()
        self.models = nn.ModuleList()
        for i in range(n):
            local_seed = base_seed + i
            set_global_seed(local_seed)
            self.models.append(resnet18_backbone(n_classes=n_classes))

    def forward(self, x):
        return torch.stack([m(x) for m in self.models], 0).mean(0)

    def get_features(self, x):
        return torch.stack([m.get_features(x) for m in self.models], 0).mean(0)

# --------------------------------------------------------------------------- #
# 3)  train/validate helpers                                                  #
# --------------------------------------------------------------------------- #
def train_one_epoch(m, ldr, opt, crit, dev):
    m.train(); loss=cor=tot=0
    for x,y in ldr:
        x,y = x.to(dev), y.to(dev)
        opt.zero_grad(); o = m(x); l = crit(o,y); l.backward(); opt.step()
        loss += l.item()*x.size(0); cor += o.argmax(1).eq(y).sum().item(); tot += y.size(0)
    return loss/tot, 100.*cor/tot

def validate(m, ldr, crit, dev):
    m.eval(); loss=cor=tot=0
    with torch.no_grad():
        for x,y in ldr:
            x,y = x.to(dev), y.to(dev); o = m(x); l = crit(o,y)
            loss += l.item()*x.size(0); cor += o.argmax(1).eq(y).sum().item(); tot += y.size(0)
    return loss/tot, 100.*cor/tot

# --------------------------------------------------------------------------- #
# 4)  loss helpers (KD / PKT)                                                 #
# --------------------------------------------------------------------------- #
def kd_loss(s, t, *, T, alpha):
    kl = F.kl_div(F.log_softmax(s/T,1), F.softmax(t/T,1), reduction="batchmean")*(T*T)
    return kl

def kd_loss1(s_logits, t_logits, labels, *, T, alpha):
    ce = F.cross_entropy(s_logits, labels)
    kl = F.kl_div(
        F.log_softmax(s_logits / T, 1),
        F.softmax(t_logits / T, 1),
        reduction="batchmean"
    ) * (T*T)
    return alpha*ce + (1-alpha)*kl

def cosine_similarity_loss(o, t, eps=1e-7):
    o = F.normalize(o, dim=1); t = F.normalize(t, dim=1)
    so = (torch.mm(o,o.t())+1)/2; st = (torch.mm(t,t.t())+1)/2
    so /= so.sum(1,keepdim=True)+eps; st /= st.sum(1,keepdim=True)+eps
    return torch.sum(st * torch.log((st+eps)/(so+eps)))

# --------------------------------------------------------------------------- #
# 5)  CAE-2 & GCN (παραμετροποιημένα σε C)                                    #
# --------------------------------------------------------------------------- #
# Define the ResNet-18 encoder
class Encoder32(nn.Module):
    def __init__(self, latent_dim=10):
        super().__init__()
        try: base = torchvision.models.resnet18(weights=None)           # ≥ 0.13
        except TypeError: base = torchvision.models.resnet18(pretrained=False)
        self.features = nn.Sequential(*list(base.children())[:-2])
        self.fc = nn.Linear(512, latent_dim)
    def forward(self, x): return self.fc(self.features(x).flatten(1))

class Decoder32(nn.Module):
    def __init__(self, latent_dim=10):
        super().__init__()
        self.fc = nn.Linear(latent_dim, 512)
        self.deconv = nn.Sequential(
            nn.ConvTranspose2d(512,256,4,2,1), nn.ReLU(True),
            nn.ConvTranspose2d(256,128,4,2,1), nn.ReLU(True),
            nn.ConvTranspose2d(128, 64,4,2,1), nn.ReLU(True),
            nn.ConvTranspose2d( 64, 64,4,2,1), nn.ReLU(True),
            nn.ConvTranspose2d( 64,  3,4,2,1), nn.Sigmoid()
        )
    def forward(self, z): return self.deconv(self.fc(z).view(z.size(0),512,1,1))

class CAE2(nn.Module):
    def __init__(self, latent_dim=10):
        super().__init__()
        self.encoder = Encoder32(latent_dim)
        self.decoder = Decoder32(latent_dim)
    def forward(self, x): z = self.encoder(x); return self.decoder(z), z

class General_Class_Network(nn.Module):
    def __init__(self, input_size=10, output_size=10, noise_std=1e-4):  # Αλλαγή από 100 σε 10
        super().__init__()
        self.linear = nn.Linear(input_size, output_size, bias=False)
        # with torch.no_grad():
        #     self.linear.weight.copy_(
        #         torch.eye(input_size, output_size) + noise_std*torch.randn(input_size,output_size)
        #     )
        self.linear.weight.data = torch.eye(input_size, output_size) + noise_std * torch.randn(input_size, output_size)
    def forward(self, x):
        return self.linear(x)

# --------------------------------------------------------------------------- #
# 6)  training wrappers (SGD + Cosine)                                        #
# --------------------------------------------------------------------------- #
def _sgd_optimizer(params, lr=0.1, momentum=0.9, weight_decay=5e-4):
    return optim.SGD(params, lr=lr, momentum=momentum, weight_decay=weight_decay)

def train_student_normal(m, tr, te, *, device, epochs):
    crit = nn.CrossEntropyLoss()
    opt = _sgd_optimizer(m.parameters(), lr=0.1)
    scheduler = CosineAnnealingLR(opt, T_max=epochs)

    m.to(device)
    for ep in range(epochs):
        m.train(); loss=cor=tot=0
        for x,y in tr:
            x,y = x.to(device), y.to(device)
            opt.zero_grad()
            o = m(x); l = crit(o,y)
            l.backward(); opt.step()
            loss += l.item()*x.size(0); cor += o.argmax(1).eq(y).sum().item(); tot += y.size(0)

        scheduler.step()
        vl_l, vl_a = validate(m, te, crit, device)
        print(f"[Student] Ep {ep+1:02}/{epochs} | Train {loss/tot:.4f}/{100.*cor/tot:.2f}% | "
              f"Val {vl_l:.4f}/{vl_a:.2f}% | LR {scheduler.get_last_lr()[0]:.6f}")
    return m

def train_student_kd(m, teacher, tr, te, *, device, epochs, T, alpha):
    crit = nn.CrossEntropyLoss()
    opt = _sgd_optimizer(m.parameters(), lr=0.1)
    scheduler = CosineAnnealingLR(opt, T_max=epochs)

    m.to(device); teacher.eval().to(device)
    for p in teacher.parameters(): p.requires_grad=False

    for ep in range(epochs):
        m.train(); loss=cor=tot=0
        for x,y in tr:
            x,y=x.to(device),y.to(device)
            opt.zero_grad()
            s=m(x); t=teacher(x)
            l=kd_loss1(s,t,y,T=T,alpha=alpha)
            l.backward(); opt.step()
            loss+=l.item()*x.size(0); cor+=s.argmax(1).eq(y).sum().item(); tot+=y.size(0)

        scheduler.step()
        vl_l,vl_a=validate(m,te,crit,device)
        print(f"[KD Student] Ep {ep+1:02}/{epochs} | Train {loss/tot:.4f}/{100.*cor/tot:.2f}% | "
              f"Val {vl_l:.4f}/{vl_a:.2f}% | LR {scheduler.get_last_lr()[0]:.6f}")
    return m

def train_student_pkt(m, teacher, tr, te, *, device, epochs, lamb):
    crit = nn.CrossEntropyLoss()
    opt = _sgd_optimizer(m.parameters(), lr=0.1)
    scheduler = CosineAnnealingLR(opt, T_max=epochs)

    m.to(device); teacher.eval().to(device)
    for p in teacher.parameters(): p.requires_grad=False

    for ep in range(epochs):
        m.train(); loss=cor=tot=0
        for x,y in tr:
            x,y=x.to(device),y.to(device)
            opt.zero_grad()
            pkt=cosine_similarity_loss(m.get_features(x),teacher.get_features(x))
            logits=m(x); ce=crit(logits,y); l=lamb*pkt+ce
            l.backward(); opt.step()
            loss+=l.item()*x.size(0); cor+=logits.argmax(1).eq(y).sum().item(); tot+=y.size(0)

        scheduler.step()
        vl_l,vl_a=validate(m,te,crit,device)
        print(f"[PKT Student] Ep {ep+1:02}/{epochs} | Train {loss/tot:.4f}/{100.*cor/tot:.2f}% | "
              f"Val {vl_l:.4f}/{vl_a:.2f}% | LR {scheduler.get_last_lr()[0]:.6f}")
    return m

# --------------------------------------------------------------------------- #
# 6b) KD+ASL training loop                                                    #
# --------------------------------------------------------------------------- #
def train_student_kd_asl(
    m, teacher, ae, ae_t, gcn_s, gcn_t,
    tr, te, * ,
    device, epochs,
    T_kd, alpha_kd,
    alpha_gcn, beta_ae, T_ae,
    lam_rec=2.,
    alpha_gcn_t=0.1, beta_ae_t=0.1, T_ae_t=5.0
):
    """
    KD+ASL training loop που ακολουθεί τα eq. (3.11)–(3.19).
    """

    # -------------------------------------------------------------- #
    #  Βοηθητικές συναρτήσεις
    # -------------------------------------------------------------- #
    def kd_kl_from_probs(s_logits, t_probs, *, T):
        # t_probs: probabilities (soft targets)
        t_probs = t_probs.detach()

        return F.kl_div(
            F.log_softmax(s_logits / T, dim=1),
            t_probs,
            reduction="batchmean"
        ) * (T * T)

    crit_ce      = nn.CrossEntropyLoss()     # CE(s(z), argmax y)
    crit_bce_log = nn.BCEWithLogitsLoss()   # BCE_logits(ŷ_s, ŷ)
    crit_bce     = nn.BCELoss()             # BCE(ŷ̃_gcn-*, s(f_s(x))^†)
    crit_mse     = nn.MSELoss()

    # SGD για student με Cosine Annealing
    opt = _sgd_optimizer(m.parameters(), lr=0.1)
    scheduler = CosineAnnealingLR(opt, T_max=epochs)

    # Adam για AE & GCN branches (πιο επιθετικό LR για καλύτερο ζ)
    gopt_s   = optim.Adam(gcn_s.parameters(),  lr=1e-5)
    gopt_t   = optim.Adam(gcn_t.parameters(),  lr=1e-5)
    gsch_s = CosineAnnealingLR(gopt_s, T_max=epochs)
    gsch_t = CosineAnnealingLR(gopt_t, T_max=epochs)
    opt_ae = optim.Adam(ae.parameters(), lr=1e-5)
    opt_ae_t = optim.Adam(ae_t.parameters(), lr=1e-5)
    ae_sch = CosineAnnealingLR(opt_ae, T_max=epochs)
    ae_t_sch = CosineAnnealingLR(opt_ae_t, T_max=epochs)

    # -------------------------------------------------------------- #
    #  Modes / device setup
    # -------------------------------------------------------------- #
    m.to(device)
    teacher.eval().to(device)
    ae.train().to(device)
    ae_t.train().to(device)
    gcn_s.train().to(device)
    gcn_t.train().to(device)

    for p in teacher.parameters():
        p.requires_grad = False  # teacher ensemble frozen

    # -------------------------------------------------------------- #
    #  Training loop
    # -------------------------------------------------------------- #
    for ep in range(epochs):
        m.train()
        loss = cor = tot = 0
        sum_y_hat = sum_y_hat_t = 0.0
        sum_ae_s = sum_ae_t = 0.0
        sum_teacher = sum_student = 0.0
        total_samples = 0

        for images, labels in tr:
            x, y = images.to(device), labels.to(device)
            labels_idx = y
            C = m.fc.out_features
            y_onehot = F.one_hot(y, num_classes=C).float()

            # Zero grads
            opt.zero_grad()
            opt_ae.zero_grad()
            opt_ae_t.zero_grad()
            gopt_s.zero_grad()
            gopt_t.zero_grad()

            # ---------------- TEACHER / STUDENT forward ---------------- #
            t_logits = teacher(x)                 # f_t(x) = t
            y_t = F.softmax(t_logits / T_kd, dim=1)      # y_t = s(t)
            s_logits = m(x)                       # ŷ_s = f_s(x)

            # ------------------- Student AE & ASL (3.11–3.13) ----------- #
            z = ae.encoder(x)                     # z = h(x)
            x_rec = ae.decoder(z)
            p_ae = F.softmax(z / T_ae, dim=1)     # s(z / T_ae)

            # g_s(y): GCN_s πάνω στο label vector
            gcn_s_logits = gcn_s(y_onehot)
            g_s_y = F.softmax(gcn_s_logits, dim=1)


            # (3.11)  Student-side ASL targets
            y_hat = (
                alpha_gcn * g_s_y +
                beta_ae   * p_ae +
                (1.0 - alpha_gcn - beta_ae) * y_onehot
            )

            # (3.13)  GCN stabilisation target για student GCN
            y_hat_gcn = (
                alpha_gcn * g_s_y +
                beta_ae   * p_ae.detach() +
                (1.0 - alpha_gcn - beta_ae) * y_onehot
            )


            p_student = F.log_softmax(s_logits, dim=1)

            loss_cls = -(y_hat.detach() * p_student).sum(dim=1).mean()

            loss_ae_s = (
                crit_ce(z, labels_idx)
                + lam_rec * crit_mse(x_rec, x)
            )

            # (3.13)  L_gcn-s
            loss_gcn_s = crit_bce(y_hat_gcn, F.softmax(s_logits, dim=1).detach())

            # ------------------- Teacher AE & ASL (3.14–3.18) ----------- #
            z_t = ae_t.encoder(x)                  # z_t = h_t(x)
            x_rec_t = ae_t.decoder(z_t)
            p_ae_t = F.softmax(z_t / T_ae_t, dim=1)

            gcn_t_logits = gcn_t(y_t)
            g_t_yt = F.softmax(gcn_t_logits, dim=1)

            # (3.14) teacher-side ASL targets
            y_hat_t = (
                alpha_gcn_t * g_t_yt +
                beta_ae_t   * p_ae_t +
                (1.0 - alpha_gcn_t - beta_ae_t) * y_t
            )

            # (3.18) teacher GCN stabilisation target
            y_hat_gcn_t = (
                alpha_gcn_t * g_t_yt +
                beta_ae_t   * p_ae_t.detach() +
                (1.0 - alpha_gcn_t - beta_ae_t) * y_t
            )

            loss_gcn_t = crit_bce(y_hat_gcn_t, F.softmax(s_logits, dim=1).detach())

            # ------------------- Distillation block (3.15, 3.17) -------- #
            # Για student distillation (3.15): χρησιμοποιούμε τα y_hat_t ως soft targets
            kd_student = kd_kl_from_probs(s_logits, y_hat_t, T=T_kd)  # KL only (distill)

            # Για teacher AE distillation (3.17): χρησιμοποιούμε τα teacher logits
            kd_teacher_ae = kd_loss(z_t, t_logits, T=T_kd, alpha=alpha_kd)

            loss_distill = kd_student
            loss_ae_t = kd_teacher_ae + lam_rec * crit_mse(x_rec_t, x)
            #     (
            #     alpha_kd * kd_student +
            #     kd_teacher_ae +
            #     lam_rec * crit_mse(x_rec_t, x)
            # ))

            # ------------------------ TOTAL LOSS (3.19) ----------------- #
            total_loss = alpha_kd * loss_cls + (1 - alpha_kd) * loss_distill + loss_ae_t + loss_gcn_s + loss_gcn_t + loss_ae_s
            total_loss.backward()

            opt.step()
            gopt_s.step()
            gopt_t.step()
            opt_ae.step()
            opt_ae_t.step()

            # -------------------- Metrics logging ------------------------ #
            with torch.no_grad():
                # ΜΕΣΟΣ ΟΡΟΣ ΤΟΥ MAX (average confidence), ΟΧΙ p(correct_label)
                max_y_hat, _     = y_hat.max(dim=1)
                max_y_hat_t, _   = y_hat_t.max(dim=1)
                max_ae_s, _      = p_ae.max(dim=1)
                max_ae_t, _      = p_ae_t.max(dim=1)
                max_teacher, _   = y_t.max(dim=1)
                max_student, _   = F.softmax(s_logits, dim=1).max(dim=1)

                sum_y_hat     += max_y_hat.sum().item()
                sum_y_hat_t   += max_y_hat_t.sum().item()
                sum_ae_s      += max_ae_s.sum().item()
                sum_ae_t      += max_ae_t.sum().item()
                sum_teacher   += max_teacher.sum().item()
                sum_student   += max_student.sum().item()
                total_samples += y.size(0)

            loss += total_loss.item() * x.size(0)
            cor  += s_logits.argmax(1).eq(labels_idx).sum().item()
            tot  += labels_idx.size(0)

        scheduler.step()
        gsch_s.step()  # gcn_s LR update (per-epoch)
        gsch_t.step()  # gcn_t LR update (per-epoch)
        ae_sch.step()
        ae_t_sch.step()

        tr_l, tr_a = loss / tot, 100. * cor / tot
        vl_l, vl_a = validate(m, te, crit_ce, device)

        mean_y_hat     = sum_y_hat     / total_samples
        mean_y_hat_t   = sum_y_hat_t   / total_samples
        mean_ae_s      = sum_ae_s      / total_samples
        mean_ae_t      = sum_ae_t      / total_samples
        mean_teacher   = sum_teacher   / total_samples
        mean_student   = sum_student   / total_samples

        print(
            f"[KD+ASL] Ep {ep+1:02}/{epochs} | "
            f"Train {tr_l:.4f}/{tr_a:.2f}% | "
            f"Val {vl_l:.4f}/{vl_a:.2f}% | "
            f"LR {scheduler.get_last_lr()[0]:.6f} | "
            f"soft(y_hat)={mean_y_hat:.3f}, "
            f"soft(y_hat_t)={mean_y_hat_t:.3f}, "
            f"soft(AE_s)={mean_ae_s:.3f}, "
            f"soft(AE_t)={mean_ae_t:.3f}, "
            f"soft(teacher)={mean_teacher:.3f}, "
            f"soft(student)={mean_student:.3f}"
        )

    return m


# --------------------------------------------------------------------------- #
# 7)  AUROC & FPR95 helpers                                                   #
# --------------------------------------------------------------------------- #
def _ood_loader(in_ds, ood_ds):
    concat = ConcatDataset([in_ds, ood_ds])
    targets = torch.cat([torch.zeros(len(in_ds)), torch.ones(len(ood_ds))])
    return DataLoader(concat, 512, False, num_workers=2), targets

def auroc_entropy_single(in_ds, ood_ds, model, dev):
    dl, tgt = _ood_loader(in_ds, ood_ds); scr = []
    with torch.no_grad():
        for x, _ in dl:
            p = F.softmax(model(x.to(dev)), 1)
            scr.append((-torch.sum(p * torch.log(p + 1e-10), 1)).cpu().numpy())
    return roc_auc_score(tgt, np.concatenate(scr))

def auroc_entropy_ensemble(in_ds, ood_ds, ens, dev):
    dl, tgt = _ood_loader(in_ds, ood_ds); scr = []
    with torch.no_grad():
        for x, _ in dl:
            p = torch.stack([F.softmax(m(x.to(dev)), 1) for m in ens.models], 0).mean(0)
            scr.append((-torch.sum(p * torch.log(p + 1e-10), 1)).cpu().numpy())
    return roc_auc_score(tgt, np.concatenate(scr))

def auroc_kunc_ensemble(in_ds, ood_ds, ens, dev):
    dl, tgt = _ood_loader(in_ds, ood_ds); scr = []
    with torch.no_grad():
        for x, _ in dl:
            stack = torch.stack([F.softmax(m(x.to(dev)), 1) for m in ens.models], 0)
            avg = stack.mean(0)
            total = -torch.sum(avg * torch.log(avg + 1e-10), 1)
            per_e = -torch.sum(stack * torch.log(stack + 1e-10), 2).mean(0)
            scr.append((total - per_e).cpu().numpy())
    return roc_auc_score(tgt, np.concatenate(scr))

def _fpr_at_95_tpr(scores, labels, *, pos_label=1):
    fpr, tpr, _ = roc_curve(labels, scores, pos_label=pos_label)
    if np.all(tpr < 0.95):
        return float(fpr[np.argmax(tpr)])
    if np.all(tpr >= 0.95):
        return float(np.min(fpr))
    return float(np.interp(0.95, tpr, fpr))

def fpr95_entropy_single(in_ds, ood_ds, model, dev):
    dl, tgt = _ood_loader(in_ds, ood_ds); scr = []
    with torch.no_grad():
        for x, _ in dl:
            p = F.softmax(model(x.to(dev)), 1)
            ent = -torch.sum(p * torch.log(p + 1e-10), 1)
            scr.append(ent.cpu().numpy())
    return _fpr_at_95_tpr(np.concatenate(scr), tgt.numpy(), pos_label=1)

def fpr95_entropy_ensemble(in_ds, ood_ds, ens, dev):
    dl, tgt = _ood_loader(in_ds, ood_ds); scr = []
    with torch.no_grad():
        for x, _ in dl:
            p = torch.stack([F.softmax(m(x.to(dev)), 1) for m in ens.models], 0).mean(0)
            ent = -torch.sum(p * torch.log(p + 1e-10), 1)
            scr.append(ent.cpu().numpy())
    return _fpr_at_95_tpr(np.concatenate(scr), tgt.numpy(), pos_label=1)


def make_loaders_for_seed(seed, tr_ds, te_ds, batch=128, num_workers=6):
    set_global_seed(seed)
    g = torch.Generator().manual_seed(seed)

    tr_loader = DataLoader(
        tr_ds, batch_size=batch, shuffle=True,
        num_workers=num_workers, worker_init_fn=_seed_worker,
        generator=g, pin_memory=True
    )
    te_loader = DataLoader(
        te_ds, batch_size=batch, shuffle=False,
        num_workers=num_workers, worker_init_fn=_seed_worker,
        generator=g, pin_memory=True
    )
    return tr_loader, te_loader


# --------------------------------------------------------------------------- #
# 8)  main: ID=CIFAR-10, OOD=CIFAR-100/TIN/SVHN/HUMAN + seeded loaders        #
# --------------------------------------------------------------------------- #
def main():
    base_seed = 42


    device = "cuda" if torch.cuda.is_available() else "cpu"
    print("Device:", device)
    C = 10  # ID = CIFAR-10 (Αλλαγή από 100 σε 10)

    t_epochs = 45
    s_epochs = 90
    alpha_kd, T_kd = 0.5, 2.5
    lambda_pkt = 1.0
    n_runs = 5  # Reduced for faster testing

    # ---------- Transforms -------------------------------------------------
    from torchvision import transforms

    # CIFAR-10 normalization (Αλλαγή από CIFAR-100)
    mean=[0.485, 0.456, 0.406]
    std=[0.229, 0.224, 0.225]

    tfm_tr10 = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(15),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])

    tfm_te10 = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])

    # Common test transform for all OOD datasets
    tfm_ood = transforms.Compose([
        transforms.Resize(32),
        transforms.CenterCrop(32),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])

    # ---------- Datasets ---------------------------------------------------
    # ID: CIFAR-10 (Αλλαγή από CIFAR-100)
    tr_c10 = torchvision.datasets.CIFAR10("./data", True, download=True, transform=tfm_tr10)
    te_c10 = torchvision.datasets.CIFAR10("./data", False, download=True, transform=tfm_te10)

    # OOD: CIFAR-100, Tiny-ImageNet, SVHN, Human Detection
    ood_c100 = torchvision.datasets.CIFAR100("./data", False, download=True, transform=tfm_ood)
    ood_tin = torchvision.datasets.ImageFolder("./tiny-imagenet-200/val", tfm_ood)
    ood_svhn = torchvision.datasets.SVHN("./data", split="test", download=True, transform=tfm_ood)
    ood_human = torchvision.datasets.ImageFolder("./human detection dataset", tfm_ood)

    # ---------- Loaders (seeded) -------------------------------------------
    g = torch.Generator(); g.manual_seed(base_seed)
    tr_loader = DataLoader(tr_c10, 128, True,  # Αλλαγή από tr_c100 σε tr_c10
                          num_workers=6, worker_init_fn=_seed_worker, generator=g, pin_memory=True)
    te_loader = DataLoader(te_c10, 128, False,  # Αλλαγή από te_c100 σε te_c10
                          num_workers=6, worker_init_fn=_seed_worker, generator=g, pin_memory=True)



    # ---------- metric containers -----------------------------------------
    teacher_accs = []; teacher_au_c100 = []; teacher_kunc_c100 = []; teacher_fpr_c100 = []
    teacher_au_tin = []; teacher_kunc_tin = []; teacher_fpr_tin = []
    teacher_au_svhn = []; teacher_kunc_svhn = []; teacher_fpr_svhn = []
    teacher_au_human = []; teacher_kunc_human = []; teacher_fpr_human = []

    sn_accs = []; sn_au_c100 = []; sn_au_tin = []; sn_au_svhn = []; sn_au_human = []
    sn_fpr_c100 = []; sn_fpr_tin = []; sn_fpr_svhn = []; sn_fpr_human = []
    kd_accs = []; kd_au_c100 = []; kd_au_tin = []; kd_au_svhn = []; kd_au_human = []
    kd_fpr_c100 = []; kd_fpr_tin = []; kd_fpr_svhn = []; kd_fpr_human = []
    pkt_accs = []; pkt_au_c100 = []; pkt_au_tin = []; pkt_au_svhn = []; pkt_au_human = []
    pkt_fpr_c100 = []; pkt_fpr_tin = []; pkt_fpr_svhn = []; pkt_fpr_human = []

    crit = nn.CrossEntropyLoss()

    # ---------- KD-ASL grid parameters ------------------------------------
    alpha_gcn_vals   = [0.1]
    beta_ae_vals     = [0.1]
    T_ae_vals        = [5.0]      # λιγότερο flat AE
    alpha_gcn_t_vals = [0.1]
    beta_ae_t_vals   = [0.1]
    T_ae_t_vals      = [5.0]
    # grid_params = list(product(alpha_gcn_vals, beta_ae_vals, T_ae_vals,
    #                            alpha_gcn_t_vals, beta_ae_t_vals, T_ae_t_vals))
    
    # ============================================================
    # KD+ASL curated grid (NEW ONLY) — T=T_t=5.0
    # tuple: (a, b, T, a_t, b_t, T_t)
    # ============================================================

    

    grid_params = [
        # -------------------- fine around 0.1 --------------------
        (0.05, 0.05, 5.0, 0.05, 0.05, 5.0),
        (0.08, 0.08, 5.0, 0.08, 0.08, 5.0),
        (0.12, 0.12, 5.0, 0.12, 0.12, 5.0),
        (0.15, 0.15, 5.0, 0.10, 0.10, 5.0),

        # -------------------- medium symmetric-ish ----------------
        (0.15, 0.10, 5.0, 0.10, 0.10, 5.0),
        (0.10, 0.15, 5.0, 0.10, 0.10, 5.0),
        (0.20, 0.10, 5.0, 0.10, 0.10, 5.0),
        (0.10, 0.20, 5.0, 0.10, 0.10, 5.0),
        (0.20, 0.15, 5.0, 0.10, 0.10, 5.0),
        (0.15, 0.20, 5.0, 0.10, 0.10, 5.0),

        # --------- teacher conservative (often best tradeoff) ------
        (0.12, 0.12, 5.0, 0.08, 0.08, 5.0),
        (0.15, 0.10, 5.0, 0.08, 0.08, 5.0),
        (0.10, 0.15, 5.0, 0.08, 0.08, 5.0),
        (0.20, 0.10, 5.0, 0.08, 0.08, 5.0),
        (0.10, 0.20, 5.0, 0.08, 0.08, 5.0),

        # -------------------- branch isolation --------------------
        # GCN-heavy (a>b)
        (0.20, 0.05, 5.0, 0.10, 0.05, 5.0),
        (0.25, 0.05, 5.0, 0.10, 0.05, 5.0),
        (0.30, 0.05, 5.0, 0.10, 0.05, 5.0),

        # AE-heavy (b>a)
        (0.05, 0.20, 5.0, 0.05, 0.10, 5.0),
        (0.05, 0.25, 5.0, 0.05, 0.10, 5.0),
        (0.05, 0.30, 5.0, 0.05, 0.10, 5.0),

        # -------------------- aggressive student -------------------
        # keep teacher mild to protect Acc
        (0.25, 0.10, 5.0, 0.10, 0.10, 5.0),
        (0.30, 0.10, 5.0, 0.10, 0.10, 5.0),
        (0.35, 0.10, 5.0, 0.10, 0.10, 5.0),
        (0.10, 0.25, 5.0, 0.10, 0.10, 5.0),
        (0.10, 0.30, 5.0, 0.10, 0.10, 5.0),
        (0.10, 0.35, 5.0, 0.10, 0.10, 5.0),

        # aggressive but teacher even more conservative
        (0.30, 0.10, 5.0, 0.05, 0.05, 5.0),
        (0.10, 0.30, 5.0, 0.05, 0.05, 5.0),
        (0.25, 0.15, 5.0, 0.05, 0.05, 5.0),
        (0.15, 0.25, 5.0, 0.05, 0.05, 5.0),
        (0.30, 0.15, 5.0, 0.05, 0.05, 5.0),
        (0.15, 0.30, 5.0, 0.05, 0.05, 5.0),

        # -------------------- teacher stronger (OOD-bias) ----------
        # try a few only (can hurt Acc)
        (0.10, 0.10, 5.0, 0.15, 0.15, 5.0),
        (0.10, 0.15, 5.0, 0.15, 0.15, 5.0),
        (0.15, 0.10, 5.0, 0.15, 0.15, 5.0),
        (0.20, 0.10, 5.0, 0.15, 0.15, 5.0),
        (0.10, 0.20, 5.0, 0.15, 0.15, 5.0),
    ]

    

    print(f"[GRID] Will run {len(grid_params)} NEW KD+ASL configs:")
    for p in grid_params:
        print("  ", p)

    kd_asl_accs_map      = defaultdict(list)
    kd_asl_au_c100_map    = defaultdict(list)
    kd_asl_au_tin_map    = defaultdict(list)
    kd_asl_au_svhn_map   = defaultdict(list)
    kd_asl_au_human_map  = defaultdict(list)
    kd_asl_fpr_c100_map   = defaultdict(list)
    kd_asl_fpr_tin_map   = defaultdict(list)
    kd_asl_fpr_svhn_map  = defaultdict(list)
    kd_asl_fpr_human_map = defaultdict(list)

    # -------- Teacher ------------------------------------------------------
    print("=== TEACHER ENSEMBLE SETUP ===")
    teacher_ckpt = "./teacher_c10_ens5.pth"
    os.makedirs(os.path.dirname(teacher_ckpt), exist_ok=True)

    # φτιάχνουμε το μοντέλο (ίδια αρχιτεκτονική πάντα)
    teacher = TeacherEnsemble(n=5, n_classes=C, base_seed=base_seed).to(device)

    if os.path.exists(teacher_ckpt):
        # Φόρτωση έτοιμου teacher
        print(f"Loading teacher ensemble weights from: {teacher_ckpt}")
        state = torch.load(teacher_ckpt, map_location=device)
        teacher.load_state_dict(state)
    else:
        # Εκπαίδευση teacher ΜΙΑ ΦΟΡΑ
        print("No pretrained teacher found. Training teacher ensemble from scratch...")
        for i, net in enumerate(teacher.models, 1):
            print(f"[Teacher {i}/5] Training ResNet-18 on CIFAR-10 …")
            train_student_normal(net, tr_loader, te_loader,
                                 device=device, epochs=t_epochs)

        # Αποθήκευση βαρών για μελλοντική χρήση
        torch.save(teacher.state_dict(), teacher_ckpt)
        print(f"Saved teacher ensemble weights to: {teacher_ckpt}")

    # Από εδώ και κάτω όπως πριν: αξιολόγηση teacher
    _, acc = validate(teacher, te_loader, crit, device)
    teacher_accs.append(acc)

    # OOD Evaluation for Teacher
    teacher_au_c100.append(auroc_entropy_ensemble(te_c10, ood_c100, teacher, device))
    teacher_kunc_c100.append(auroc_kunc_ensemble(te_c10, ood_c100, teacher, device))
    teacher_fpr_c100.append(fpr95_entropy_ensemble(te_c10, ood_c100, teacher, device))

    teacher_au_tin.append(auroc_entropy_ensemble(te_c10, ood_tin, teacher, device))
    teacher_kunc_tin.append(auroc_kunc_ensemble(te_c10, ood_tin, teacher, device))
    teacher_fpr_tin.append(fpr95_entropy_ensemble(te_c10, ood_tin, teacher, device))

    teacher_au_svhn.append(auroc_entropy_ensemble(te_c10, ood_svhn, teacher, device))
    teacher_kunc_svhn.append(auroc_kunc_ensemble(te_c10, ood_svhn, teacher, device))
    teacher_fpr_svhn.append(fpr95_entropy_ensemble(te_c10, ood_svhn, teacher, device))

    teacher_au_human.append(auroc_entropy_ensemble(te_c10, ood_human, teacher, device))
    teacher_kunc_human.append(auroc_kunc_ensemble(te_c10, ood_human, teacher, device))
    teacher_fpr_human.append(fpr95_entropy_ensemble(te_c10, ood_human, teacher, device))

    # --------------------------------------------------------------------- #
    # AE Pretrain (once)                                                    #
    # --------------------------------------------------------------------- #
    print("[Autoencoder] Preparing CAE2(10) on CIFAR-10 …")
    lamda = 2.0

    ae_ckpt_full = "./ae_c10_ae_full.pth"
    ae_ckpt_enc = "./ae_c10_ae_encoder.pth"

    ae_base = CAE2(latent_dim=C).to(device)

    if os.path.exists(ae_ckpt_full):
        print(f"[AE] Found checkpoint: {ae_ckpt_full} -> loading weights.")
        state = torch.load(ae_ckpt_full, map_location=device)
        ae_base.load_state_dict(state)
    else:
        print("[AE] No checkpoint found. Pretraining CAE2(10) from scratch and saving weights …")

        opt_ae = torch.optim.Adam(ae_base.parameters(), lr=1e-4)
        mse, ce = nn.MSELoss(), nn.CrossEntropyLoss()
        softmax = nn.Softmax(dim=1)
        num_epochs = 100

        ae_base.train()
        for ep in range(num_epochs):
            run_loss = 0.0
            for x, y in tr_loader:
                x, y = x.to(device), y.to(device)
                opt_ae.zero_grad()

                z = ae_base.encoder(x)
                x_hat = ae_base.decoder(z)

                loss = lamda * mse(x_hat, x) + ce(softmax(z), y)  # kept as you had it
                loss.backward()
                opt_ae.step()

                run_loss += loss.item()

            print(f"[AE] Epoch {ep + 1:03}/{num_epochs} | Loss {run_loss / len(tr_loader):.4f}")

        ae_base.eval()

        torch.save(ae_base.state_dict(), ae_ckpt_full)
        torch.save(ae_base.encoder.state_dict(), ae_ckpt_enc)
        print(f"[AE] Saved full AE to {ae_ckpt_full} and encoder to {ae_ckpt_enc}")

    ae_base.eval()

    # =================== runs =============================================
    for run in range(n_runs):
        print(f"\n=== RUN {run+1}/{n_runs} ===")
        # *** ΚΡΙΤΙΚΗ ΑΛΛΑΓΗ: διαφορετικό seed για ΚΑΘΕ run ***
        run_seed = base_seed + run * 1000  # διαφορετικό seed για κάθε run
        set_global_seed(run_seed)

        # *** ΚΡΙΤΙΚΗ ΑΛΛΑΓΗ: Δημιουργία dataloaders ΜΕΣΑ στο run loop ***
        g = torch.Generator()
        g.manual_seed(run_seed)  # διαφορετικό seed για dataloaders

        # ID: CIFAR-10 με διαφορετικό seed σε κάθε run
        tr_c10 = torchvision.datasets.CIFAR10("./data", True, download=True, transform=tfm_tr10)
        te_c10 = torchvision.datasets.CIFAR10("./data", False, download=True, transform=tfm_te10)

        tr_loader = DataLoader(tr_c10, 128, True,
                               num_workers=6, worker_init_fn=_seed_worker, generator=g, pin_memory=True)
        te_loader = DataLoader(te_c10, 128, False,
                               num_workers=6, worker_init_fn=_seed_worker, generator=g, pin_memory=True)

        # -------- Student baseline ----------------------------------------
        print("Training Student Baseline...")
        s = resnet18_backbone(n_classes=C)
        train_student_normal(s, tr_loader, te_loader,
                            device=device, epochs=s_epochs)
        _, acc = validate(s, te_loader, crit, device)
        sn_accs.append(acc)
        
        sn_au_c100.append(auroc_entropy_single(te_c10, ood_c100, s, device))
        sn_au_tin.append(auroc_entropy_single(te_c10, ood_tin, s, device))
        sn_au_svhn.append(auroc_entropy_single(te_c10, ood_svhn, s, device))
        sn_au_human.append(auroc_entropy_single(te_c10, ood_human, s, device))
        
        sn_fpr_c100.append(fpr95_entropy_single(te_c10, ood_c100, s, device))
        sn_fpr_tin.append(fpr95_entropy_single(te_c10, ood_tin, s, device))
        sn_fpr_svhn.append(fpr95_entropy_single(te_c10, ood_svhn, s, device))
        sn_fpr_human.append(fpr95_entropy_single(te_c10, ood_human, s, device))
        
        # -------- Student KD ----------------------------------------------
        print("Training Student with KD...")
        s = resnet18_backbone(n_classes=C)
        train_student_kd(s, teacher, tr_loader, te_loader,
                        device=device, epochs=s_epochs,
                        T=T_kd, alpha=alpha_kd)
        _, acc = validate(s, te_loader, crit, device)
        kd_accs.append(acc)
        
        kd_au_c100.append(auroc_entropy_single(te_c10, ood_c100, s, device))
        kd_au_tin.append(auroc_entropy_single(te_c10, ood_tin, s, device))
        kd_au_svhn.append(auroc_entropy_single(te_c10, ood_svhn, s, device))
        kd_au_human.append(auroc_entropy_single(te_c10, ood_human, s, device))
        
        kd_fpr_c100.append(fpr95_entropy_single(te_c10, ood_c100, s, device))
        kd_fpr_tin.append(fpr95_entropy_single(te_c10, ood_tin, s, device))
        kd_fpr_svhn.append(fpr95_entropy_single(te_c10, ood_svhn, s, device))
        kd_fpr_human.append(fpr95_entropy_single(te_c10, ood_human, s, device))
        
        # -------- Student PKT ---------------------------------------------
        print("Training Student with PKT...")
        s = resnet18_backbone(n_classes=C)
        train_student_pkt(s, teacher, tr_loader, te_loader,
                         device=device, epochs=s_epochs,
                         lamb=lambda_pkt)
        _, acc = validate(s, te_loader, crit, device)
        pkt_accs.append(acc)
        
        pkt_au_c100.append(auroc_entropy_single(te_c10, ood_c100, s, device))
        pkt_au_tin.append(auroc_entropy_single(te_c10, ood_tin, s, device))
        pkt_au_svhn.append(auroc_entropy_single(te_c10, ood_svhn, s, device))
        pkt_au_human.append(auroc_entropy_single(te_c10, ood_human, s, device))
        
        pkt_fpr_c100.append(fpr95_entropy_single(te_c10, ood_c100, s, device))
        pkt_fpr_tin.append(fpr95_entropy_single(te_c10, ood_tin, s, device))
        pkt_fpr_svhn.append(fpr95_entropy_single(te_c10, ood_svhn, s, device))
        pkt_fpr_human.append(fpr95_entropy_single(te_c10, ood_human, s, device))

        # -------- KD+ASL grid ---------------------------------------------
        print("Training KD+ASL variants...")
        print("[Autoencoder] Using pretrained CAE2(10) weights for this run …")

        tr_ds = tr_c10
        te_ds = te_c10

        for a, b, t, a_t, b_t, t_t in grid_params:
            print(f"[GRID KD+ASL] a={a},b={b},T={t}|a_t={a_t},b_t={b_t},T_t={t_t}")

            # loaders με ίδιο seed για fairness ανά config
            tr_loader, te_loader = make_loaders_for_seed(run_seed, tr_ds, te_ds, batch=128)

            gcn_s = General_Class_Network(input_size=C, output_size=C).to(device)
            gcn_t = General_Class_Network(input_size=C, output_size=C).to(device)

            # ΝΕΟ: κάνουμε fresh instances αλλά φορτώνουμε τα pretrained weights
            ae = CAE2(latent_dim=C).to(device)
            ae_t = CAE2(latent_dim=C).to(device)

            ae.load_state_dict(ae_base.state_dict())
            ae_t.load_state_dict(ae_base.state_dict())

            s = resnet18_backbone(n_classes=C).to(device)

            train_student_kd_asl(
                s, teacher, ae, ae_t, gcn_s, gcn_t,
                tr_loader, te_loader,
                device=device, epochs=s_epochs,
                T_kd=T_kd, alpha_kd=alpha_kd,
                alpha_gcn=a, beta_ae=b, T_ae=t,
                lam_rec=2.,
                alpha_gcn_t=a_t, beta_ae_t=b_t, T_ae_t=t_t
            )

            _, acc = validate(s, te_loader, crit, device)
            key = (a, b, t, a_t, b_t, t_t)

            kd_asl_accs_map[key].append(acc)
            kd_asl_au_c100_map[key].append(auroc_entropy_single(te_c10, ood_c100, s, device))
            kd_asl_au_tin_map[key].append(auroc_entropy_single(te_c10, ood_tin, s, device))
            kd_asl_au_svhn_map[key].append(auroc_entropy_single(te_c10, ood_svhn, s, device))
            kd_asl_au_human_map[key].append(auroc_entropy_single(te_c10, ood_human, s, device))

            kd_asl_fpr_c100_map[key].append(fpr95_entropy_single(te_c10, ood_c100, s, device))
            kd_asl_fpr_tin_map[key].append(fpr95_entropy_single(te_c10, ood_tin, s, device))
            kd_asl_fpr_svhn_map[key].append(fpr95_entropy_single(te_c10, ood_svhn, s, device))
            kd_asl_fpr_human_map[key].append(fpr95_entropy_single(te_c10, ood_human, s, device))

    # =================== summary ===========================================
    hdr = "{:<60} {:>7}  {:>8} {:>8} {:>8} {:>8}  {:>8} {:>8} {:>8} {:>8}"
    print("\n" + "="*120)
    print("SUMMARY (ID=CIFAR-10; OOD: C100 / TIN / SVHN / HUMAN)")
    print("="*120)
    print(hdr.format(
        "Model", "Acc",
        "AU-C100", "AU-TIN", "AU-SVHN", "AU-HUMAN",
        "FPR-C100", "FPR-TIN", "FPR-SVHN", "FPR-HUMAN"
    ))
    print("-"*120)

    def _ms(x): return f"{np.mean(x):.3f}±{np.std(x):.3f}"

    print(hdr.format(
        "Ensemble-5 (Teacher)",
        _ms(teacher_accs),
        _ms(teacher_au_c100), _ms(teacher_au_tin), _ms(teacher_au_svhn), _ms(teacher_au_human),
        _ms(teacher_fpr_c100), _ms(teacher_fpr_tin), _ms(teacher_fpr_svhn), _ms(teacher_fpr_human)
    ))

    print(hdr.format(
        "ResNet-18 (Student)",
        _ms(sn_accs),
        _ms(sn_au_c100), _ms(sn_au_tin), _ms(sn_au_svhn), _ms(sn_au_human),
        _ms(sn_fpr_c100), _ms(sn_fpr_tin), _ms(sn_fpr_svhn), _ms(sn_fpr_human)
    ))

    print(hdr.format(
        "ResNet-18 (KD)",
        _ms(kd_accs),
        _ms(kd_au_c100), _ms(kd_au_tin), _ms(kd_au_svhn), _ms(kd_au_human),
        _ms(kd_fpr_c100), _ms(kd_fpr_tin), _ms(kd_fpr_svhn), _ms(kd_fpr_human)
    ))

    print(hdr.format(
        "ResNet-18 (PKT)",
        _ms(pkt_accs),
        _ms(pkt_au_c100), _ms(pkt_au_tin), _ms(pkt_au_svhn), _ms(pkt_au_human),
        _ms(pkt_fpr_c100), _ms(pkt_fpr_tin), _ms(pkt_fpr_svhn), _ms(pkt_fpr_human)
    ))

    def _fmt_params(a, b, t, a_t, b_t, t_t):
        return f"a={a:.2f},b={b:.2f},T={t:.1f} | a_t={a_t:.2f},b_t={b_t:.2f},T_t={t_t:.1f}"

    for key in sorted(kd_asl_accs_map.keys()):
        acc = kd_asl_accs_map[key]  # <-- ΑΥΤΟ ΕΛΕΙΠΕ
        a, b, t, a_t, b_t, t_t = key
        label = "KD+ASL " + _fmt_params(a, b, t, a_t, b_t, t_t)

        print(hdr.format(
            label[:60],  # για να χωράει στον fixed-width πίνακα
            _ms(acc),
            _ms(kd_asl_au_c100_map[key]), _ms(kd_asl_au_tin_map[key]),
            _ms(kd_asl_au_svhn_map[key]), _ms(kd_asl_au_human_map[key]),
            _ms(kd_asl_fpr_c100_map[key]), _ms(kd_asl_fpr_tin_map[key]),
            _ms(kd_asl_fpr_svhn_map[key]), _ms(kd_asl_fpr_human_map[key])
        ))

        # extra line ώστε να φαίνονται ΟΛΑ τα params, χωρίς κόψιμο:
        print(" " * 2 + _fmt_params(a, b, t, a_t, b_t, t_t))

    print("="*120)
    print("Done.")

# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    main()
